(function(){
const STORE="marine_data_v5";
const PROGRAM={
A:{name:"WORKOUT A — PUSH",exercises:[["Chest Press",3,"8–12"],["Incline Chest Press",3,"8–12"],["Shoulder Press",3,"8–12"],["Lateral Raise",3,"12–15"],["Triceps Pressdown",3,"10–15"],["Overhead Triceps Extension",3,"10–15"]]},
B:{name:"WORKOUT B — PULL",exercises:[["Lat Pulldown",3,"8–12"],["Seated Cable Row",3,"8–12"],["Rear-Delt Fly / Reverse Pec Deck",3,"12–15"],["Cable or Machine Curl",3,"10–15"],["Hammer Curl",3,"10–15"],["Preacher Curl",2,"10–15"]]}
};
let activeWorkout=null;
function key(d=new Date()){return d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0")}
function data(){try{return JSON.parse(localStorage.getItem(STORE)||"{}")}catch(e){return {}}}
function save(d){localStorage.setItem(STORE,JSON.stringify(d))}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function toast(t,m){try{if(typeof mcToast==="function")mcToast(t,m);else if(typeof showModal==="function")showModal(t,m)}catch(e){}}
function refresh(){try{if(typeof update==="function")update()}catch(e){} updateMiles()}
function C(){return document.getElementById("phase2Content")}
function title(a,b){document.getElementById("phase2Title").textContent=a;document.getElementById("phase2Subtitle").textContent=b||"App remembers. Coach decides."}
function show(){const o=document.getElementById("phase2FitnessOverlay");o.classList.add("active");o.setAttribute("aria-hidden","false")}
window.closeFitnessPhase2=function(){const o=document.getElementById("phase2FitnessOverlay");o.classList.remove("active");o.setAttribute("aria-hidden","true");activeWorkout=null};
window.openFitnessPhase2=function(){title("FITNESS","Choose today's mission.");C().innerHTML='<div class="phase2WorkoutChoices"><button class="yellow" type="button" onclick="openRunPhase2()">RUN</button><button type="button" onclick="openGymPhase2()">GYM DAY</button></div><div class="phase2Miles">This week: <strong>'+weeklyMiles().toFixed(2)+' running miles</strong></div>';show()};
function parseTime(v){const p=String(v||"").trim().split(":").map(Number);if((p.length!==2&&p.length!==3)||p.some(n=>!Number.isFinite(n)||n<0))return null;if((p.length===2&&p[1]>=60)||(p.length===3&&(p[1]>=60||p[2]>=60)))return null;const s=p.length===2?p[0]*60+p[1]:p[0]*3600+p[1]*60+p[2];return s>0?s:null}
function fmt(s){s=Math.round(s);const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),x=s%60;return h?String(h).padStart(2,"0")+":"+String(m).padStart(2,"0")+":"+String(x).padStart(2,"0"):String(m)+":"+String(x).padStart(2,"0")}
function pace(d,s){return d>0&&s>0?fmt(s/d)+"/mi":"—"}
window.openRunPhase2=function(){title("RUN","Distance + time + optional notes.");C().innerHTML='<label>Distance (miles)</label><input id="phase2RunDistance" type="number" min="0.01" step="0.01" inputmode="decimal" placeholder="2.00"><label>Total time (MM:SS or HH:MM:SS)</label><input id="phase2RunTime" type="text" inputmode="numeric" placeholder="23:42"><div class="phase2RunResult">Average pace: <strong id="phase2RunPace">—</strong></div><label>Optional notes</label><textarea id="phase2RunNotes" placeholder="Ran first mile continuously; run/walk second mile."></textarea><button class="yellow" type="button" onclick="saveRunPhase2()">COMPLETE RUN</button>';show();["phase2RunDistance","phase2RunTime"].forEach(id=>document.getElementById(id).addEventListener("input",runPace))};
function runPace(){const d=parseFloat(document.getElementById("phase2RunDistance").value),s=parseTime(document.getElementById("phase2RunTime").value);document.getElementById("phase2RunPace").textContent=(d>0&&s)?pace(d,s):"—"}
window.saveRunPhase2=function(){const dist=parseFloat(document.getElementById("phase2RunDistance").value),raw=document.getElementById("phase2RunTime").value.trim(),sec=parseTime(raw);if(!(dist>0)){toast("Run","Enter a valid distance.");return}if(!sec){toast("Run","Enter time as MM:SS or HH:MM:SS.");return}const d=data(),k=key(),e=d[k]||{};e.runSession={distance:+dist.toFixed(2),timeSeconds:sec,time:fmt(sec),pace:pace(dist,sec),notes:document.getElementById("phase2RunNotes").value.trim(),completedAt:new Date().toISOString()};e.workout=true;e.cardio=true;e.workoutType="RUN";e.notes=e.runSession.notes||"Run completed.";d[k]=e;save(d);refresh();closeFitnessPhase2();toast("Run Logged",dist.toFixed(2)+" mi • "+e.runSession.pace)};
function latest(name){const d=data(),ks=Object.keys(d).sort().reverse();for(const k of ks){const g=d[k]&&d[k].gymSession;if(!g||!Array.isArray(g.exercises))continue;const x=g.exercises.find(e=>e.name===name);if(x&&Array.isArray(x.sets))return x}return null}
function exercise(ex,ei){const [name,n,target]=ex,p=latest(name),prev=p&&p.sets.length?p.sets.map(s=>(s.weight??"—")+"×"+(s.reps??"—")).join(" | "):"No previous session";let sets="";for(let i=0;i<n;i++){const w=p&&p.sets[i]&&p.sets[i].weight!=null?p.sets[i].weight:"";sets+='<div class="phase2Set"><b>Set '+(i+1)+'</b><input class="phase2Weight" data-ex="'+ei+'" data-set="'+i+'" type="number" min="0" step="0.5" inputmode="decimal" placeholder="Weight" value="'+esc(w)+'"><input class="phase2Reps" data-ex="'+ei+'" data-set="'+i+'" type="number" min="0" step="1" inputmode="numeric" placeholder="Reps"></div>'}return '<div class="phase2Exercise"><h3>'+esc(name)+'</h3><div class="small">Target: '+n+' × '+target+'</div><div class="phase2Previous">Previous: '+esc(prev)+'</div>'+sets+'</div>'}
window.openGymPhase2=function(){title("GYM DAY","Choose Push or Pull.");C().innerHTML='<div class="phase2WorkoutChoices"><button class="yellow" type="button" onclick="renderGymPhase2(\'A\')">WORKOUT A — PUSH</button><button type="button" onclick="renderGymPhase2(\'B\')">WORKOUT B — PULL</button></div>';show()};
window.renderGymPhase2=function(code){activeWorkout=code;const p=PROGRAM[code];title(p.name,"Enter actual weight and reps for every working set.");let body='<div class="phase2ToggleGrid"><div class="phase2Toggle"><label>Warm-up<br><span class="small">5 min • 2.5 speed • incline 15</span><input id="phase2Warmup" type="checkbox" checked></label></div><div class="phase2Toggle"><label>Cooldown / Stretch<input id="phase2Cooldown" type="checkbox"></label></div><div class="phase2Toggle"><label>Red-light therapy<input id="phase2RedLight" type="checkbox"></label></div><div class="phase2Toggle"><label>Massage chair<input id="phase2Massage" type="checkbox"></label></div></div>';p.exercises.forEach((x,i)=>body+=exercise(x,i));body+='<button class="yellow" type="button" onclick="completeGymPhase2()">COMPLETE WORKOUT</button>';C().innerHTML=body};
window.completeGymPhase2=function(){if(!activeWorkout||!PROGRAM[activeWorkout])return;const p=PROGRAM[activeWorkout],exercises=[];let missing=false;p.exercises.forEach((ex,ei)=>{const sets=[];for(let si=0;si<ex[1];si++){const w=document.querySelector('.phase2Weight[data-ex="'+ei+'"][data-set="'+si+'"]').value,r=document.querySelector('.phase2Reps[data-ex="'+ei+'"][data-set="'+si+'"]').value;if(w===""||r==="")missing=true;sets.push({weight:w===""?null:+w,reps:r===""?null:+r})}exercises.push({name:ex[0],target:ex[2],sets})});if(missing){toast("Gym Day","Enter weight and reps for every working set.");return}const d=data(),k=key(),e=d[k]||{},warm=document.getElementById("phase2Warmup").checked,cool=document.getElementById("phase2Cooldown").checked,red=document.getElementById("phase2RedLight").checked,massage=document.getElementById("phase2Massage").checked;e.gymSession={workout:activeWorkout,name:p.name,warmup:warm,cooldown:cool,redLight:red,massageChair:massage,exercises,completedAt:new Date().toISOString()};e.workout=true;e.cardio=warm;e.workoutType="GYM DAY — WORKOUT "+activeWorkout;e.redLight=red;e.massageChair=massage;e.massageChairSkipped=!massage;e.notes=p.name+" completed.";d[k]=e;save(d);try{if(typeof checkWorkoutMilestoneGoblin==="function")checkWorkoutMilestoneGoblin()}catch(err){}refresh();closeFitnessPhase2();toast("Workout Logged",p.name+" saved. App remembers. Coach decides.")};
function monday(){const n=new Date(),day=n.getDay(),diff=day===0?-6:1-day,m=new Date(n);m.setDate(n.getDate()+diff);m.setHours(0,0,0,0);return m}
function weeklyMiles(){const d=data(),m=monday();let t=0;Object.keys(d).forEach(k=>{const x=new Date(k+"T12:00:00");if(x>=m&&d[k]&&d[k].runSession)t+=Number(d[k].runSession.distance)||0});return t}
function updateMiles(){const x=document.getElementById("phase2WeeklyMiles");if(x)x.textContent=weeklyMiles().toFixed(2)+" mi"}
function exportText(){const e=data()[key()]||{};let out="";if(e.runSession){const r=e.runSession;out+="\n\nRUN\nDistance: "+Number(r.distance||0).toFixed(2)+" mi\nTime: "+r.time+"\nAverage Pace: "+r.pace+"\nNotes: "+(r.notes||"None")+"\nWeekly Running Miles: "+weeklyMiles().toFixed(2)+" mi"}if(e.gymSession){const g=e.gymSession;out+="\n\nGYM DAY — WORKOUT "+g.workout+"\nWarm-up (5 min, speed 2.5, incline 15): "+(g.warmup?"YES":"NO")+"\nCooldown / Stretch: "+(g.cooldown?"YES":"NO")+"\nRed-light therapy: "+(g.redLight?"YES":"NO")+"\nMassage chair: "+(g.massageChair?"YES":"NO");g.exercises.forEach(ex=>out+="\n"+ex.name+": "+ex.sets.map(s=>s.weight+"×"+s.reps).join(" | "))}return out}
function patchSummary(){if(typeof window.generateSummary!=="function"||window.generateSummary.__phase2)return;const old=window.generateSummary;window.generateSummary=function(){const r=old.apply(this,arguments),box=document.getElementById("summaryBox");if(box){let base=String(box.value||r||"");base=base.replace(/\n\nRUN\n[\s\S]*?(?=\n\nGYM DAY — WORKOUT|\s*$)/,"").replace(/\n\nGYM DAY — WORKOUT [AB]\n[\s\S]*$/,"");box.value=base.trim()+exportText();return box.value}return r};window.generateSummary.__phase2=true}
document.addEventListener("DOMContentLoaded",function(){updateMiles();setTimeout(patchSummary,100);setTimeout(patchSummary,1200);const o=document.getElementById("phase2FitnessOverlay");if(o)o.addEventListener("click",e=>{if(e.target===o)closeFitnessPhase2()})});
setTimeout(function(){patchSummary();try{if(typeof generateSummary==="function")generateSummary()}catch(e){}},2200);
})();